name: Publicar Imagem Docker

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build e Push para GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem
        run: |
          IMAGE=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE:latest .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push da imagem
        run: docker push $IMAGE:latest